---
driver:
  name: vagrant
provisioner:
  name: chef_zero

# Test all of the platforms that we support for this cookbook.   
platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04
  - name: centos-7.0
  - name: centos-6.5

# Each major component of the recipe should be tested independently.    
suites:
  - name: bootnode
    run_list:
      - 'recipe[blp-bcpc::bootnode]'
  - name: headnode
    run_list:
      - 'recipe[blp-bcpc::headnode]'
  - name: worknode
    run_list:
      - 'recipe[blp-bcpc::worknode]'
