source 'https://supermarket.chef.io'
cookbook 'openstack-block-storage', github: 'stackforge/cookbook-openstack-block-storage', tag: 'stable/juno'
cookbook 'openstack-common', github: 'stackforge/cookbook-openstack-common', tag: 'stable/juno'
cookbook 'openstack-dashboard', github: 'stackforge/cookbook-openstack-dashboard', tag: 'stable/juno'
cookbook 'openstack-compute', github: 'stackforge/cookbook-openstack-compute', tag: 'stable/juno'
cookbook 'openstack-identity', github: 'stackforge/cookbook-openstack-identity', tag: 'stable/juno'
cookbook 'openstack-image', github: 'stackforge/cookbook-openstack-image', tag: 'stable/juno'
cookbook 'openstack-network', github: 'stackforge/cookbook-openstack-network', tag: 'stable/juno'
cookbook 'openstack-object-storage', github: 'stackforge/cookbook-openstack-object-storage', tag: 'stable/juno'
cookbook 'openstack-metering', github: 'stackforge/cookbook-openstack-telemetry', tag: 'stable/juno'
metadata
