name             'blp-bcpc'
maintainer       'Bloomberg Finance L.P.'
maintainer_email 'jbellone@bloomberg.net'
license          'Apache 2.0'
description      'Installs/Configures blp-bcpc - Bloomberg Clustered Private Cloud'
long_description 'Installs/Configures blp-bcpc - Bloomberg Clustered Private Cloud'
version          '0.1.0'

supports 'redhat', '~> 6.5'
supports 'centos', '~> 6.5'
supports 'ubuntu', '= 12.04'
supports 'ubuntu', '= 14.04'

depends 'apt'
depends 'apache2'
depends 'ceph'
depends 'chef-sugar'
depends 'firewall'
depends 'iptables'
depends 'haproxy'
depends 'ntp'
depends 'percona'
depends 'rabbitmq'
depends 'resolver'
depends 'ubuntu'
depends 'yum'
depends 'yum-centos'
depends 'yum-epel'
