name 'blp-bcpc'
maintainer 'Bloomberg Finance L.P.'
maintainer_email 'jbellone@bloomberg.net'
license 'Apache 2.0'
description 'Wrapper cookbook to install and configure BCPC - Bloomberg Clustered Private Cloud.'
long_description 'Wrapper cookbook to install and configure BCPC - Bloomberg Clustered Private Cloud.'
version '0.1.0'

supports 'ubuntu', '>= 14.04'
supports 'centos', '>= 7.1'
supports 'redhat', '>= 7.1'

depends 'apt'
depends 'ceph'
depends 'chef-client'
depends 'chef-server'
depends 'chef-sugar'
depends 'dhcp'
depends 'firewall'
depends 'haproxy'
depends 'ntp'
depends 'os-hardening'
depends 'postgresql'
depends 'pdns'
depends 'rabbitmq-cluster'
depends 'resolver'
depends 'selinux'
depends 'ubuntu'
depends 'yum'
depends 'yum-centos'
depends 'yum-epel'

depends 'openstack-block-storage'
depends 'openstack-common'
depends 'openstack-dashboard'
depends 'openstack-compute'
depends 'openstack-identity'
depends 'openstack-image'
depends 'openstack-network'
depends 'openstack-object-storage'
depends 'openstack-metering'
